[build]
  functions = "functions"

[dev]
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "https://paul.blueboxonline.com/api/v1/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200